{"uuid": "617bd54a-44a2-43be-8ab1-cc6ba217fc58", "children": ["65ac96c6-c069-43ab-841f-1d106a41982f"], "befores": [{"name": "driver_init", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'D\\:\\\\Android\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s e948c834 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.\r\nThis adb server's $ADB_VENDOR_KEYS is not set\r\nTry 'adb kill-server' if that seems wrong.\r\nOtherwise check for a confirmation dialog on your device.'; Code: '1'\n\n", "trace": "  File \"D:\\Program Files\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\ylh--Python文件\\ylh\\ECshopAPP移动端测试\\scripts\\conftest.py\", line 6, in driver_init\n    driver = open_app()\n  File \"D:\\ylh--Python文件\\ylh\\ECshopAPP移动端测试\\common\\base.py\", line 18, in open_app\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    proxy\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1578553925530, "stop": 1578553925774}], "start": 1578553925530, "stop": 1578553925945}